# Site settings
title: Mosaico.io News and Blog
email: feedback@mosaico.io
description: > # News from Mosaico Template Editor.
# url: "http://mosaico.io" # the base hostname & protocol for your site
fullcanonicalurl: "https://mosaico.io"
staticurl: "https://voidlabs.github.io/mosaico.io"
basepath: "" # used for host-relative paths
description: "Mosaico is the first open source email template editor proudly brought to you by VOXmail: it is powerful and free! The email template builder supports responsive design and live wysiwyg editing."
keywords: "responsive email designer, email editor, free email builder, email template creator, open source mail editor, newsletter editor, template builder"
titlepostfix: " | Mosaico.io"
mosaico_version: 0.18.7
editor_path: editor-0.18.7.html
# google_analytics_id: UA-61367795-1
# piwikpro_id: "d2d1ac4f-5015-4a6d-a26f-bd99bbb89141"
# piwikpro_url: "https://mosaico.containers.piwik.pro/"

repository: voidlabs/mosaico.io

twitter_username: mosaicoeditor
github_username:  bago
permalink: /:categories/:title/
excerpt_separator: <!--more-->


# Build settings
# TEST FOR NEW GITHUB FEATURE markdown: redcarpet
highlighter: rouge
redcarpet:
  extensions: ["footnotes", "smart", "hard_wrap", "no_intra_emphasis", "tables"]
